{{- if .Values.global.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.global.serviceAccount.name }}
  namespace: {{ $.Values.global.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ $.Values.global.serviceAccount.arn }}
{{- end }}